//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountMyDartMaui.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountMyDartMaui.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bot points to gain.
        /// </summary>
        internal static string BotPageBotPointsToGain {
            get {
                return ResourceManager.GetString("BotPageBotPointsToGain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accept Throws.
        /// </summary>
        internal static string BotPageButton1 {
            get {
                return ResourceManager.GetString("BotPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu End game quicker.
        /// </summary>
        internal static string BotPageButton2 {
            get {
                return ResourceManager.GetString("BotPageButton2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Round.
        /// </summary>
        internal static string BotPageRound_ {
            get {
                return ResourceManager.GetString("BotPageRound ", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your points to gain.
        /// </summary>
        internal static string BotPageYourPointsToGain {
            get {
                return ResourceManager.GetString("BotPageYourPointsToGain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your throws.
        /// </summary>
        internal static string BotPageYourThrows {
            get {
                return ResourceManager.GetString("BotPageYourThrows", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accept All Throws.
        /// </summary>
        internal static string GamePageButton1 {
            get {
                return ResourceManager.GetString("GamePageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu End Game.
        /// </summary>
        internal static string GamePageButton2 {
            get {
                return ResourceManager.GetString("GamePageButton2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To Gain:.
        /// </summary>
        internal static string GamePagePointsToGain {
            get {
                return ResourceManager.GetString("GamePagePointsToGain", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Round.
        /// </summary>
        internal static string GamePageRound {
            get {
                return ResourceManager.GetString("GamePageRound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Throws:.
        /// </summary>
        internal static string GamePageThrows {
            get {
                return ResourceManager.GetString("GamePageThrows", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Accept.
        /// </summary>
        internal static string MainPageButton {
            get {
                return ResourceManager.GetString("MainPageButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string MainPageButton2 {
            get {
                return ResourceManager.GetString("MainPageButton2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose Game Mode:.
        /// </summary>
        internal static string MainPageGameModeChoose {
            get {
                return ResourceManager.GetString("MainPageGameModeChoose", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Choose how many people will play:.
        /// </summary>
        internal static string MainPagePlayersAmount {
            get {
                return ResourceManager.GetString("MainPagePlayersAmount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add Player.
        /// </summary>
        internal static string PlayerPageButton1 {
            get {
                return ResourceManager.GetString("PlayerPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start Game.
        /// </summary>
        internal static string PlayerPageButton2 {
            get {
                return ResourceManager.GetString("PlayerPageButton2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go Back.
        /// </summary>
        internal static string PlayerPageButton3 {
            get {
                return ResourceManager.GetString("PlayerPageButton3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DELETE.
        /// </summary>
        internal static string PlayerPageDelete {
            get {
                return ResourceManager.GetString("PlayerPageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter Player&apos;s Name.
        /// </summary>
        internal static string PlayerPageEnterPlayerName {
            get {
                return ResourceManager.GetString("PlayerPageEnterPlayerName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No players have been added.
        /// </summary>
        internal static string PlayerPageNoPlayers {
            get {
                return ResourceManager.GetString("PlayerPageNoPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Start new game.
        /// </summary>
        internal static string ScoreboardPageButton1 {
            get {
                return ResourceManager.GetString("ScoreboardPageButton1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No Winner!.
        /// </summary>
        internal static string ScoreboardPageNoWinner {
            get {
                return ResourceManager.GetString("ScoreboardPageNoWinner", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player Ranking .
        /// </summary>
        internal static string ScoreboardPageRanking {
            get {
                return ResourceManager.GetString("ScoreboardPageRanking", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Scoreboard.
        /// </summary>
        internal static string ScoreboardPageTitle {
            get {
                return ResourceManager.GetString("ScoreboardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Winner:.
        /// </summary>
        internal static string ScoreboardPageWinner {
            get {
                return ResourceManager.GetString("ScoreboardPageWinner", resourceCulture);
            }
        }
    }
}
